-- CREATE EXTENSION IF NOT EXISTS "UUID-OSSP";
-- CREATE EXTENSION IF NOT EXISTS "PGCRYPTO";

CREATE TABLE PUBLIC.PRODUCTS (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    CODE        TEXT        NOT NULL,
    NAME        TEXT        NOT NULL,
    DESCRIPTION TEXT        NOT NULL,
    IMAGE_URL   TEXT        NULL,
    CONSTRAINT PK_PRODUCTS  PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.COLORS (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    CODE        TEXT        NOT NULL,
    NAME        TEXT        NOT NULL,
    HEX_CODE    TEXT        NOT NULL,
    CONSTRAINT PK_COLORS    PRIMARY KEY (ID)
    -- CONSTRAINT UK_COLORS_CODE UNIQUE (CODE)
);

CREATE TABLE PUBLIC.PRODUCT_COLORS (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    PRODUCT_ID  UUID        NOT NULL,
    COLOR_ID    UUID        NOT NULL,
    CONSTRAINT PK_PRODUCT_COLORS PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_COLORS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS (ID),
    CONSTRAINT FK_PRODUCT_COLORS_COLOR FOREIGN KEY (COLOR_ID) REFERENCES PUBLIC.COLORS (ID)
    -- CONSTRAINT UK_PRODUCT_COLORS UNIQUE (PRODUCT_ID, COLOR_ID)
);


CREATE TABLE PUBLIC.PRODUCT_SIZES (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    PRODUCT_ID  UUID        NOT NULL,
    NAME        TEXT        NOT NULL,
    CONSTRAINT PK_PRODUCT_SIZES PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_SIZES_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PUBLIC.PRODUCTS (ID)
    -- CONSTRAINT UK_PRODUCT_SIZES UNIQUE (PRODUCT_ID, NAME)
);

CREATE TABLE PUBLIC.SKUS (
    ID                UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT        TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT        TIMESTAMP   NOT NULL DEFAULT NOW(),
    PRODUCT_COLOR_ID  UUID  NOT NULL,
    PRODUCT_SIZE_ID   UUID  NOT NULL,
    PRICE NUMERIC     NOT NULL DEFAULT 0,
    CONSTRAINT PK_SKUS PRIMARY KEY (ID),
    CONSTRAINT FK_SKUS_PRODUCT_COLOR_ID FOREIGN KEY (PRODUCT_COLOR_ID) REFERENCES PUBLIC.PRODUCT_COLORS (ID),
    CONSTRAINT FK_SKUS_PRODUCT_SIZE_ID FOREIGN KEY (PRODUCT_SIZE_ID) REFERENCES PUBLIC.PRODUCT_SIZES (ID),
    CONSTRAINT UK_SKUS UNIQUE (PRODUCT_COLOR_ID, PRODUCT_SIZE_ID)
);

CREATE TABLE PUBLIC.CUSTOMERS (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    NAME        TEXT        NOT NULL,
    EMAIL       TEXT        NOT NULL,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
    -- CONSTRAINT UK_CUSTOMER_EMAIL UNIQUE (EMAIL)
);

CREATE TYPE ORDER_STATUS  AS ENUM ('DRAFT', 'CANCELED', 'SENT');

CREATE TABLE PUBLIC.ORDERS (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    CUSTOMER_ID UUID        NOT NULL,
    TOTAL       NUMERIC     NOT NULL DEFAULT 0,
    STATUS      ORDER_STATUS NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
    CONSTRAINT FK_ORDERS_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMERS (ID)
);

CREATE TABLE PUBLIC.ORDER_ITEMS (
    ID          UUID        NOT NULL DEFAULT UUID_GENERATE_V4(),
    CREATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMP   NOT NULL DEFAULT NOW(),
    SKU_ID      UUID        NOT NULL,
    ORDER_ID    UUID        NOT NULL,
    QUANTITY    NUMERIC     NOT NULL DEFAULT 0,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_ITEMS_SKU_ID FOREIGN KEY (SKU_ID) REFERENCES PUBLIC.SKUS (ID),
    CONSTRAINT FK_ORDER_ITEMS_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES PUBLIC.ORDERS (ID)
);