  DROP TABLE IF EXISTS PUBLIC.ORDER_ITEMS;
  DROP TABLE IF EXISTS PUBLIC.SKUS;
  DROP TABLE IF EXISTS PUBLIC.PRODUCT_SIZES;
  DROP TABLE IF EXISTS PUBLIC.PRODUCT_COLORS;
  DROP TABLE IF EXISTS PUBLIC.COLORS;
  DROP TABLE IF EXISTS PUBLIC.PRODUCTS;
  DROP TABLE IF EXISTS PUBLIC.ORDERS;
  DROP TABLE IF EXISTS PUBLIC.CUSTOMERS;
  
  DROP TYPE PUBLIC.ORDER_STATUS;